modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="imageframe"
version="1.0.1"
displayName="Image Frame"
logoFile="icon.png"
description='''Place images from URLs on your walls using Shift+RMB on any item frame or painting.'''
authors="Dseelis"

[[dependencies.steamcore]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.227,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.steamcore]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"